### ISSUE TITLE
On the top you wrote

### ISSUE THREAD

**Issue by GrosSacASac** [corysimmons/concat-file-array-cli#1]
you can just use cat instead. concat-file-array-cli works on Windows so you can write cross platform npm scripts

Useless I don t think so

**Comment by corysimmons** [comment]
Oh! I'm glad it's useful for you.

Doesn't Windows have access to a Linux Bash nowadays?

**Comment by GrosSacASac** [comment]
It is possible but not easy to set up in older versions than Windows 10

**Comment by corysimmons** [comment]
Ah I see. I don't blame you for not wanting to migrate to the spyware edition of Windows (gonna miss out on that sweet DirectX upgrade though!).

I'm sure there's some npm package out there that is better than this, but if this works for you then I'm happy. 👍
